#!/usr/bin/env bash

# Original date: 2022-01-28
# Revised date: 2023-07-09

# Usage: ./make_article post-name.html

readonly base_dir="$HOME/workspace/personal_website/WWW/markdown-posts/"
cd "${base_dir}" || exit
sourcefile="$1"

# add <article id> with date at line 1
postdate=$(date +%Y%m%d)
sed -i "1i\
<article id=\"$postdate\">" "$sourcefile"

# add <time datetime> with date within h3 element
h3date=$(date +%B-%d-%Y)
timedate=$(date +%Y-%m-%d)
textdate=$(date "+%B %d, %Y")
sed -i "2a\
    <h3 id=\"$h3date\"><time datetime=\"$timedate\">$textdate</time></h3>" "$sourcefile" 

# add </article> as the last line
sed -i '$a\
</article>' "$sourcefile"
