#!/usr/bin/env bash

# Date: 2023-04-03
# Steps
# 1. Convert markdown post to HTML
# 2. Add custom HTML elements and attributes to HTML post
# 3. Insert post into WWW/index.html page at top
# 4. Add post to table of contents
# 5. Create RSS XML block for new post
# 6. Insert RSS XML into WWW/index.xml
# 7. Create makefile to automate above and publishing

md2html() {
  local sourcefile="$1"
  pandoc -f gfm -t html "$sourcefile" > \
    "$(basename -s md "$sourcefile")"html
}

add_html() {
  sed -e "2 s/>/><time datetime=$(date +%Y-%m-%d)>/"
  sed -e "2 s/<\/h3>/<\/time><\/h3>/"
  sed -e "1i <article id=$(date +%Y%m%d)>"
  sed -e '$a</article>'
}

insert_post() {
}

add_toc() {
}

create_rss() {
}

insert_rss() {
}

main() {
  md2html
  add_html
  insert_post
  add_toc
  create_rss
  insert_rss
}

main()
