#!/bin/bash

## Generates a RSS entry for the most recent blog post for ../WWW/index.xml
## Date: 10/11/2020
## Sean Burns
## Usage: ./makerss.sh

## Part 1: Get values

# Create a date for the <lastBuildDate> xml element.
date -u | \
  sed 's/ /, /' | \
  sed 's/.M UTC/GMT/' > tmp.xml

# Extract and Insert Title value from the index.html file.
grep 'h2 id=' ../WWW/index.html | \
  head -n1 | \
  xmlstarlet sel -t -v '/h2' >> tmp.xml

echo -e "\n" >> tmp.xml

# Create a link using base URL and the <h2> element from index.hml.
printf 'https://cseanburns.net/WWW/index.html#' >> tmp.xml
grep 'h2 id=' ../WWW/index.html | \
  head -n1 | \
  xmlstarlet sel -T -t -v '/h2/@id' >> tmp.xml

# Copy the date from <lastBuildDate> to a new line for the <pubDate> XML element.
printf '1t4\nw\n' | \
  ed -s tmp.xml

# Delete the blank line. Need to investigate so that this isn't needed. 
printf '3d\nw\n' | \
  ed -s tmp.xml

# Copy link from above to use with the <guid> element
printf '3t4\nw\n' | \
  ed -s tmp.xml

## Part 2: Add XML tags

sed -i '1 s/^/<lastBuildDate>/' tmp.xml
sed -i '1 s/$/<\/lastBuildDate>/' tmp.xml

sed -i '2 s/^/<title>/' tmp.xml
sed -i '2 s/$/<\/title>/' tmp.xml

sed -i '3 s/^/<link>/' tmp.xml
sed -i '3 s/$/<\/link>/' tmp.xml

sed -i '4 s/^/<pubDate>/' tmp.xml
sed -i '4 s/$/<\/pubDate>/' tmp.xml

sed -i '5 s/^/<guid>/' tmp.xml
sed -i '5 s/$/<\/guid>/' tmp.xml

ed -s tmp.xml << EOF
2i
<item>
.
6a
</item>
.
wq
EOF
