#!/bin/bash

## Generates a RSS entry for the most post for ../WWW/index.xml
## Date: 10/11/2020
## Sean Burns
## Usage: ./make-rss

## Part 1: Get values

# Create a date for the <lastBuildDate> element.
rss_date="$(date -R)"
echo "$rss_date" > tmp.xml

# Get title from most recent entry
# Add <title> tags
grep 'h2 id=' ../WWW/index.html | \
  head -n1 | \
  grep -o '[A-Z][a-z]*' | \
  sed -e ':a; N; $!ba; s/\n/ /g' \
  -e 's/^/<title>/' \
  -e 's/$/<\/title>/' >> tmp.xml

# Copy the date line for the <pubdate> element
sed -i '1H;$G' tmp.xml 

# Delete blank line
sed -i '3d' tmp.xml

# Add date elements
sed -i '1 s/^/<lastBuildDate>/' tmp.xml
sed -i '1 s/$/<\/lastBuildDate>/' tmp.xml

sed -i '3 s/^/<pubDate>/' tmp.xml
sed -i '3 s/$/<\/pubDate>/' tmp.xml

## Create a link using the baseurl and the <h2> element from index.html.
#printf 'https://cseanburns.net/WWW/index.html#' >> tmp.xml
#grep 'h2 id=' ../WWW/index.html | \
#  head -n1 | \
#  xmlstarlet sel -T -t -v '/h2/@id' >> tmp.xml
#
## Copy the date from <lastBuildDate> to a new line in order to create the <pubDate> XML element.
#printf '1t4\nw\n' | \
#  ed -s tmp.xml
#
## Delete a blank line. Need to investigate so that this isn't needed. 
#printf '3d\nw\n' | \
#  ed -s tmp.xml
#
## Copy link from above to use with the <guid> XML element
#printf '3t4\nw\n' | \
#  ed -s tmp.xml
#
### Part 2: Add all of the XML tags for all the values above
#
#sed -i '1 s/^/<lastBuildDate>/' tmp.xml
#sed -i '1 s/$/<\/lastBuildDate>/' tmp.xml
#
#sed -i '2 s/^/<title>/' tmp.xml
#sed -i '2 s/$/<\/title>/' tmp.xml
#
#sed -i '3 s/^/<link>/' tmp.xml
#sed -i '3 s/$/<\/link>/' tmp.xml
#
#sed -i '4 s/^/<pubDate>/' tmp.xml
#sed -i '4 s/$/<\/pubDate>/' tmp.xml
#
#sed -i '5 s/^/<guid>/' tmp.xml
#sed -i '5 s/$/<\/guid>/' tmp.xml
#
## Add the opening and closing <item> XML elements for the new entry block
#ed -s tmp.xml << EOF
#2i
#<item>
#.
#6a
#</item>
#.
#wq
#EOF
