#!/usr/bin/bash

# Original date: 2022-01-28

# After running ``makepost`` (in .bash_functions), which will convert the
# markdown file into an HTML one this ed(1) command below add some additional
# HTML elements etc to make the post ready for the main index.html file.

# Usage: ./make_article post-name.html

post="$1"

ed -s "$post" << 'EOF'
0i
<article id="
.
1r !date +\%Y\%m\%d
1,2j
1a
">
.
1,2j
3s/[0-9]\">/\
&\

.
4r !date +\%Y-\%m-\%d
4a
<time datetime="
.
6a
">
.
8s/<\/h3>/<\/time><\/h3>
3,8j
$a
</article>

.
wq
EOF

