#!/bin/bash

# Date: 2020-03-27
# This script generates a list of entries from ../WWW/index.html (the blog),
# saves and inserts the most recent item into the table of contents on
# ../index.html.
#
# Usage: ./WWW-toc-generator
   
blogfile="../WWW/index.html"

# Create list item from other HTML tags
grep "h2 id=" "$blogfile" | sed -e 's/h2 id/a href/' -e\
's/h2/a/' -e\
's/\"/\"WWW\/index.html\#/' -e\
's/^/\<li\>/' -e\
's/$/\<\/li\>/' > tmp.html

# Get the most recent entry only; comment out if want the entire list
head -n1 tmp.html > tmp1.html

# Add the most recent entry to the top of the table of contents in ../index.html
sed -i "/ol type/ a $(cat tmp1.html)" ../index.html

# Cleanup
trash tmp.html tmp1.html
