#!/bin/bash

# Original Date: 2020-03-27
#
# This script creates a <li> item from the most recent daybook post in
# ../WWW/index.html (the daybook) and inserts the item into the table of
# contents on ../index.html.
#
# Usage: ./WWW-toc-generator
   
daybookfile="../WWW/index.html"

# Get the title of the most recent daybook entry. Substitute the original
# HTML tags for the ones needed for the <li> line in the table of contents
# in ../index.html
grep "h2 id=" "$daybookfile" | head -n1 | \
    sed -e 's/h2 id/a href/' -e\
    's/h2/a/' -e\
    's/\"/\"WWW\/index.html\#/' -e\
    's/^/\<li\>/' -e\
    's/$/\<\/li\>/' > tmp.html

# Add the new <li> entry to the top of the table of contents in ../index.html
sed -i "/ol type/ a $(cat tmp.html)" ../index.html

# Cleanup
trash tmp.html
